#!/usr/bin/env bash

## Fix java applications
export _JAVA_AWT_WM_NONREPARENTING=1
export JDK_JAVA_OPTIONS='-Dawt.useSystemAAFontSettings=on -Dswing.aatext=true -Dswing.defaultlaf=com.sun.java.swing.plaf.gtk.GTKLookAndFeel'

# Terminate already running polybar, eww, picom, sxhkd and dunst instances
processes=("picom" "polybar" "sxhkd" "dunst")

for process in "${processes[@]}"; do
	if pidof -q $process; then
		pkill -9 -x $process 2>/dev/null
		sleep 0.1
	fi
done

pgrep -x sxhkd >/dev/null || sxhkd &

xrandr --output Virtual-1 --primary --mode 2560x1440 --pos 0x0 --rotate normal --output Virtual-2 --off --output Virtual-3 --off --output Virtual-4 --off &

spice-vdagent &

$HOME/.config/polybar/launch.sh &

dunst -config $HOME/.config/dunst/dunstrc &

if [[ "$NUM_OF_MONITORS" -ge 1 ]]; then
	$XDG_CONFIG_HOME/bspwm/scripts/display-inoutput/multimonitor
fi

workspaces() {
	name=1
	for monitor in $(bspc query -M); do
		bspc monitor "$monitor" -n "$name" -d '1' '2' '3' '4' '5' '6'
		bspc monitor "$monitor" -n "$name" -d '' '' '' '' '' ''

		((name++))
	done
}
workspaces

bspc config border_radius 4
bspc config border_width 4
bspc config top_padding 40
bspc config bottom_padding 0
bspc config left_padding 0
bspc config right_padding 0
bspc config single_monocle true
bspc config click_to_focus true
bspc config history_aware_focus true
bspc config pointer_modifier mod4
bspc config pointer_motion_interval 5
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner
bspc config remove_disabled_monitors true
bspc config merge_verlapping_monitors true
bspc config window_gap 12
bspc config split_ratio 0.52
bspc config borderless_monocle true
bspc config gapless_monocle true

# Windows Border Settings
bspc config focused_border_color "#3888A0"
bspc config normal_border_color "#D4D4D4"
bspc config active_border_color "#073642"
bspc config inactive_border_color "#24BEB0"
bspc config normal_border_color "#5D6ADE"
bspc config active_border_color "#5D1CE6"

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

# Transparency
/usr/local/bin/picom -b --config $HOME/.config/picom/picom.conf --experimental-backends --animations --animation-for-open-window fly-in --animation-window-mass 0.5 --animation-stiffness 350 &

# Wallpaper
/usr/bin/feh --bg-fill $HOME/Pictures/wallpapers/space-man-2560x1440.jpg &

# Secondary Monitor Setup
bspc config -m 2 top_padding 3
bspc config -m 2 bottom_padding 3
bspc config -m 2 right_padding 3
bspc config -m 2 left_padding 3
