#!/usr/bin/env bash

dir="$HOME/.config/rofi/launchers/keybindings"
theme="properties"

awk '/^[a-z]/ && last {print "<small>",$0,"\t",last,"</small>"} {last=""} /^#/{last=$0}' "$XDG_CONFIG_HOME"/sxhkd/sxhkdrc |
	column -t -s $'\t' |
	rofi -theme ${dir}/${theme}.rasi \
		-dmenu \
		-i -markup-rows -no-show-icons-width 1000 \
		-lines 15 -yoffset 40
